apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis-db.fullname" . }}
  labels:
    {{- include "aegis-db.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "aegis-db.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis-db.fullname" . }}-headless
  labels:
    {{- include "aegis-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.server.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.server.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.server.raftPort }}
      targetPort: raft
      protocol: TCP
      name: raft
  selector:
    {{- include "aegis-db.selectorLabels" . | nindent 4 }}
---
{{- if .Values.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis-db.fullname" . }}-external
  labels:
    {{- include "aegis-db.labels" . | nindent 4 }}
  {{- with .Values.externalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.externalService.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "aegis-db.selectorLabels" . | nindent 4 }}
{{- end }}
